# Generated by Django 4.2.4 on 2023-11-28 12:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home_anpr", "0002_alter_tenant_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vehicle",
            old_name="model",
            new_name="vehicle_color",
        ),
    ]
